version: 2.1

jobs:
  build:
    working_directory: ~/core-repo
    docker:
      - image: circleci/node:12.5.0
    steps:
      - checkout
      - run:
          name: install-yarn
          command: 'sudo npm install -g yarn@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint
